# Generated by Django 4.2.10 on 2024-02-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_station_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='identifiers',
            field=models.TextField(null=True),
        ),
    ]
